import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';

import { useSession } from 'next-auth/react';
import ReactApexChart from 'react-apexcharts';

const series = [44, 55, 13, 43, 22];
const options = {
  chart: {
    width: 380,
    type: 'pie',
  },
  labels: ['Team A', 'Team B', 'Team C', 'Team D', 'Team E'],
  responsive: [
    {
      breakpoint: 480,
      options: {
        chart: {
          width: 200,
        },
        legend: {
          position: 'bottom',
        },
      },
    },
  ],
};

const Dashboard: NextPage = () => {
  const { data: session, status } = useSession({ required: true });
  if (status === 'authenticated') {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta
            name="description"
            content="Generated by create next app"
          />
          <link
            rel="icon"
            href="/favicon.ico"
          />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome {session?.user?.name?.split(' ')[0]} to{' '}
            <a href="https://nextjs.org">LifeTracker!</a>
          </h1>
          <ReactApexChart
            options={options}
            series={series}
            type="pie"
            width={380}
          />
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    );
  }
};

export default Dashboard;
